when:
  - event: [push, pull_request]
    branch: [devel]

steps:
  - name: deploy-staging
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: STAGING_HOST
      username:
        from_secret: STAGING_USER
      key:
        from_secret: STAGING_SSH_KEY
      port: 22
      script:
        - cd /srv/projects/backend_rafifah
        - git checkout devel
        - git pull origin devel
        - docker compose up -d --build
        - docker compose exec -T app php artisan optimize:clear
        - docker compose exec -T app php artisan migrate --force
    when:
      event: push
      branch: devel